[build]
  publish = ".next"
  command = "npm ci --legacy-peer-deps && npm run build"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--legacy-peer-deps"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[dev]
  command = "npm run dev"
  port = 3000

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    # Cache avec stale-while-revalidate pour éviter les erreurs 500
    Cache-Control = "public, max-age=0, s-maxage=60, stale-while-revalidate=86400"

# Headers pour les assets statiques
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Redirections SEO - Domaines dupliqués
[[redirects]]
  from = "http://www.velocit-ai.fr/*"
  to = "https://velocit-ai.fr/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.velocit-ai.fr/*"
  to = "https://velocit-ai.fr/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://velocit-ai.fr/*"
  to = "https://velocit-ai.fr/:splat"
  status = 301
  force = true

# Bloquer la page parasite
[[redirects]]
  from = "/ff44f9df"
  to = "/"
  status = 301
  force = true

# Configuration pour Next.js (géré automatiquement par @netlify/plugin-nextjs)